### ISSUE TITLE
GARCIA LORCA SENS A/B non disponible

### ISSUE THREAD

**Issue by Sulexa** [MathisAlepis/lovelace-tam-card#1]
Bonjour,
Déjà merci pour la card ça va être très pratique.
Par contre petit souci de mon côté, quand je mets un arrêt de la ligne 4 par exemple Saint-Martin ou Restanque on a qu'un choix de direction indiqué Garcia Lorca. Sauf que la ligne 4 fait une boucle sur Garcia Lorca avec comme indication sens A ou B.

Comment reproduire ?
Mettre Saint-Martin ou Restanque en tant qu'Arrêt.
Dans direction un seul choix est possible :  Garcia Lorca 

Attendu ?
Deux choix de direction Garcia Lorca Sens A & Garcia Lorca Sens B

**Comment by MathisAlepis** [comment]
Bonjour,

Merci pour le retour et les détails concernant l'erreur.

Effectivement, je n'avais pas pensé aux différents sens de circulation de la ligne 4.

Je viens de faire les modifications sur le serveur, vous pouvez dès à présent choisir le sens de direction sur la ligne 4.
