### ISSUE TITLE
Pas d'affichage de la carte dans lovelace

### ISSUE THREAD

**Issue by Ikari34** [MathisAlepis/lovelace-tam-card#3]
Bonjour,

Et merci beaucoup pour le developpement de cette carte.
Malheureusement je croie que je n'ai pas bien compris comment l'intégrer dans mon home assistant. Je l'ai installé via hacs puis dans mon lovelace j'ajoute la carte en mettant ce code :
type: custom:tam-card
stop: POMPIGNANE
direction: GARCIA LORCA SENS A
Mais rien ne s'affiche. Est-ce un souci dans la syntaxe ou ai-je loupé une étape dans l'installation de la carte ?

Autre chose. Est-ce possible de récupérer la donnée de l'horaire du passage du tram dans un sensor ha ?

**Comment by MathisAlepis** [comment]
Bonjour,

Merci pour votre retour et veuillez excuser ma réponse tardive.

Après investigation, je viens de mettre à jour tout le système de récupération des données de la TAM vers la carte, vous devriez donc plus avoir de soucis avec le code "yaml". 
Si jamais, il est aussi possible de configurer la carte en utilisant l'éditeur visuel, ce qui évite les erreurs.

En ce qui concerne la récupération des horaires dans un sensor, cela n'est pas possible, vu que mon plugin est une "interface" et non pas une "integration". 
Mais je développerai peut-être à l'avenir une intégration le permettant.

Cordialement,
Mathis

**Comment by Ikari34** [comment]
Merci Mathis pour cette maj mais sur mon lovelace ça n'a pas changé grand chose : toujours aucun affichage et en configuration automatique la liste déroulante ne m'affiche aucune station. 
Je pense que j'ai loupé un truc sur l'intégration de ton app.
J'ai ajouté ta carte via hacs mais c'est tout.  Il faut faire autre chose ? Comment intégrer ton repo directement dans hass ?
Encore merci pour ton développement et ton aide. 

Cordialement

**Comment by MathisAlepis** [comment]
Normalement, il suffit juste d'installer la carte avec HACS et c'est tout.

Peux-tu essayer de désinstaller et réinstallé la carte en pensant à redémarrer ton installation à chaque étape et de vider le cache de ton navigateur ?

Si le problème persiste, tu peux rejoindre ce serveur [Discord](https://discord.gg/8Qx6Knt5) ou tu pourras m'envoyer plus de détail comme des captures d'écran de ta console du navigateur.

**Comment by Ikari34** [comment]
C'est parfait ça fonctionne nickel après desinstallation de ton intégration puis redémarrage et réinstallation et enfin redemarrage de home assistant.
Un grand merci Mathis !
Et je surveille ton repo si jamais le temps et l'envie te prend de faire une integration qui ajouterait le sensor. 
Bon week-end et de joyeuses fêtes de fin d'année à toi.
Cordialement,
Xavier

**Comment by Ikari34** [comment]
Re Mahis,
Pourrais-tu prevoir la personnalisation du fond de la carte ? Le marron foncé sur le fond de la carte rend quasi illisible la lecture de l'information du passage du tram. (J'ai inséré ta carte sur un un dashboard d'écran à encre électronique type liseuse, et ta carte ressort en quasi noir rendant la lecture impossible).

**Comment by MathisAlepis** [comment]
Bonjour,

j'ai compris ta problématique. J'ai donc rajouté la possibilité de modifier la couleur du fond, mais aussi celle du texte. N'hésite pas à installer la mise à jour pour pouvoir y accéder.

P.S.  Il te suffira d'ajouter ceci à ta carte : 
```
backgroundColor: red
textColor: white
```
ou tu peux aussi mettre les code hexa de la couleur souhaitée.
```
backgroundColor: '#FF0000'
textColor: '#FFFFFF'
```

Bonne journée.
Mathis

**Comment by Ikari34** [comment]
Merci Mathis : cest parfait !
